//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurumsalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string Username { get; set; }
        public string Mail { get; set; }
        public string Contents { get; set; }
        public int BlogId { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
